pipeline {
    agent any
    environment {
        // AWS_REGION = 'ap-northeast-1'
        // CLUSTER_NAME = 'EKS_CLOUD'
        BACKEND_IMAGE = "lutfar1996/backend:${BUILD_NUMBER}"  // Set the backend image tag dynamically
    }
    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/Lutfar1996/response-demo.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    // Ensure you're in the directory where package.json exists
                    dir('backend') {
                        sh 'npm install'
                    }
                }
            }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    // Provide Docker registry credentials and ensure it's wrapped in a block
                    withDockerRegistry([credentialsId: 'docker', url: 'https://index.docker.io/v1/']) {
                        dir('backend') {
                            // Build Docker image, tag it using Jenkins build number, and push to Docker Hub
                            sh "docker build -t ${BACKEND_IMAGE} ."
                            sh "docker push ${BACKEND_IMAGE}"  // Push the tagged image
                        }
                    }
                }
            }
        }
        // stage('Update Kubeconfig for EKS') {
        //     steps {
        //         script {
        //             withAWS(credentials: 'aws-credentials') {
        //                 // Update the kubeconfig to point to the correct EKS cluster
        //                 sh "aws eks --region ${AWS_REGION} update-kubeconfig --name ${CLUSTER_NAME}"
        //             }
        //         }
        //     }
        // }
        // stage('Deploy to EKS') {
        //     steps {
        //         script {
        //             // Replace image tag in the backend manifest file with the Jenkins build number
        //             sh "sed -i 's|lutfar1996/backend:latest|${BACKEND_IMAGE}|g' backend-deployment.yaml"
        //             // Apply the updated deployment YAML file to the EKS cluster
        //             sh "kubectl apply -f backend-deployment.yaml"
        //         }
        //     }
        // }
    }
}
